### ISSUE TITLE
Issue while fetching resources-data with filter

### ISSUE THREAD

**Issue by marvsman** [passbolt/go-passbolt#12]
Hello there,
i'm currently playing around with the Passbolt-API and this beautiful written go module.

While playing around, an error occured while fetching resources filtered by groups. **See:** `FilterIsSharedWithGroup`

**Request:**

	groupuuids := make([]string, 0)

	for _, element := range Groups {
		groupuuids = append(groupuuids, element.GroupUUID)
	}

	res, err := client.GetResources(ctx, &pbapi.GetResourcesOptions{
		FilterIsSharedWithGroup: []string{groupuuids[1]},
	})
	if err != nil {
		log.Fatal(err)
		panic(err)
	}
	fmt.Println(res)

**Log:**
`2022/04/12 16:14:29 Error API JSON Response Status: Message: An Internal Error Has Occurred., Body: ""`

**Server-Error-Log:**
`2022-04-12 14:25:02 Error: [TypeError] Argument 1 passed to App\Controller\Component\QueryStringComponent::validateFilterGroup() must be of the type string, bool given, called in /usr/share/php/passbolt/src/Controller/Component/QueryStringComponent.php on line 299 in /usr/share/php/passbolt/src/Controller/Component/QueryStringComponent.php on line 543
Request URL: /resources.json?api-version=v2&filter%5Bis-shared-with-group%5D%5B%5D=641d3d65-3ce6-4e6d-ba94-034bbd86f04b
Client IP: xx.xx.xxx.xxx`

In result, the same issue occures with usage of go-cli.

Looks like there is some sort of TypeError even thoo i provided the required type (Array of group-uuids as string).
I tried to locate the issue with another filter, which runs through exactly the same filter-validator, but in another request: That worked perfectly. 

I took a quick look at the validators. Turns out `is-shared-with-group` is executes `validateFilterGroup` which only takes one string/group-uuid as value. 

**Switch-Case:**

                    case 'has-groups':
                        self::validateFilterGroups($values, $filterName);
                        break;
                    case 'has-parent':
                        self::validateFilterParentFolders($values, $filterName);
                        break;
                    case 'is-shared-with-group':
                        self::validateFilterGroup($values, $filterName);
                        break;

**The validator function:**

    public static function validateFilterGroup(string $groupId, string $filterName): bool
    {
        if (!Validation::uuid($groupId)) {
            throw new Exception(__('"{0}" is not a valid group id for filter {1}.', $groupId, $filterName));
        }

        return true;
    }

I tried to use `validateFilterGroups` (like in `has-groups`) instead of `validateFilterGroup` to work with an array. That threw me the same error (but i'm far away from a php-expert lol).

To continue working on my project, i modified the **GetResourcesOptions**-type to let `FilterIsSharedWithGroup` use a single string instead of an array:

	// GetResourcesOptions are all available query parameters
	type GetResourcesOptions struct {
		FilterIsFavorite                   bool     `url:"filter[is-favorite],omitempty"`
		FilterIsSharedWithGroup   string   `url:"filter[is-shared-with-group],omitempty"

That worked pretty well for me but it's restricting me to filter through multiple groups at once.

***All my packages are up-to-date. The server is running on a debian environment.***

Does anyone know if this is an known issue?

Would be nice if somebody could fix this (:

Have a good one, 
marvsman

**Comment by speatzle** [comment]
Hi, thanks for Reporting.
From roughly reading the source and git history the "is-shared-with-group" filter has only ever taken a single group id.
This type mismatch seems to have been introduced when I updated the known get options to be more in line with the docs 
(the API docs were missing most options before that point so the options were extracted from the source code so maybe the at the time new docs were wrong about this?): https://github.com/passbolt/go-passbolt/commit/ea631ac6a54fbe1a95ff24d1bb277753ea1c6647

I'll release a new version tomorrow with the correct type for go-passbolt and go-passbolt-cli.

Cheers.

**Comment by speatzle** [comment]
Released with https://github.com/passbolt/go-passbolt/releases/tag/v0.5.7

**Comment by marvsman** [comment]
> Released with https://github.com/passbolt/go-passbolt/releases/tag/v0.5.7

Thanks for that quick support :)
